default: &default
  adapter: postgresql
  user: <%= ENV['CALENDAR_DATABASE_USER'] %>
  password: <%= ENV['CALENDAR_DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: myrubyblog

test:
  <<: *default
  database: myrubyblog
